name: Cargo Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    strategy:
      matrix:
        rust_version:
          - stable
          - beta
          - nightly
          - 1.85.0  # MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
      - run: sudo apt-get install -y valgrind
      # Run the benchmarks multiple times to ensure that the code that
      # calculates the delta between runs works properly
      - run: cargo bench
      - run: cargo bench
      - run: cargo bench

  lint:
    strategy:
      matrix:
        rust_version:
          - stable
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          components: 'clippy, rustfmt'
      - run: cargo fmt --all --check
      - run: cargo clippy --all --all-targets -- --deny=warnings
